### ISSUE TITLE
 sum(results['SC_metric']) KeyError: 'SC_metric'

### ISSUE THREAD

**Issue by zyxcambridge** [Rorisis/Co-Occ#11]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ] 6016/6019, 1.2 task/s, elapsed: 4902s, ETA:     2s
 Evaluating nuScenes occupancy: SC IoU = 0.408, SSC mIoU = 0.202
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ] 6017/6019, 1.2 task/s, elapsed: 4903s, ETA:     2s
 Evaluating nuScenes occupancy: SC IoU = 0.408, SSC mIoU = 0.202
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ] 6018/6019, 1.2 task/s, elapsed: 4903s, ETA:     1s
 Evaluating nuScenes occupancy: SC IoU = 0.408, SSC mIoU = 0.202
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 1.2 task/s, elapsed: 4904s, ETA:     0sTraceback (most recent call last):
  File "tools/test.py", line 317, in <module>
    main()
  File "tools/test.py", line 313, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/zyx/code/Co-Occ/projects/mmdet3d_plugin/datasets/nuscenes_lss_dataset.py", line 207, in evaluate
    return self.evaluate_ssc(results, logger, **kwargs)
  File "/home/zyx/code/Co-Occ/projects/mmdet3d_plugin/datasets/nuscenes_lss_dataset.py", line 165, in evaluate_ssc
    evaluation_semantic = sum(results['SC_metric'])
KeyError: 'SC_metric'

**Comment by Rorisis** [comment]
Thanks for your question. You may consider using "bash tools/dist_test.sh $YOUR_CONFIG $YOUR_CKPT $GPU_NUM" as we update our guidance file.
